version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started
  build:
    commands:
      - echo Build started on `date`
      - echo Tagging the Docker image...
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$RELEASE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:production
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:production
      - printf '[{"name":"$IMAGE_REPO_NAME","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:production"}]' "$AWS_ACCOUNT_ID" "$AWS_DEFAULT_REGION" "$IMAGE_REPO_NAME"> .codepipeline.json
  post_build:
    commands:
      - echo Build completed
artifacts:
  files: .codepipeline.json
